# Generated by Django 2.0.3 on 2018-11-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False, help_text='Attended or did not attend the event')),
            ],
            options={
                'ordering': ['event'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of Sofar event', unique=True)),
                ('location', models.CharField(help_text='Location of Sofar Event', max_length=255)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the person', max_length=255)),
                ('last_name', models.CharField(blank=True, help_text='Last name of the person', max_length=255)),
                ('email', models.EmailField(help_text='Email of the person', max_length=254, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(help_text='Sofar event detail', on_delete=django.db.models.deletion.CASCADE, to='attendance.Event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='person',
            field=models.ForeignKey(help_text='Detail of person attending the event', on_delete=django.db.models.deletion.CASCADE, to='attendance.Person'),
        ),
    ]
