# Generated by Django 2.0.3 on 2018-12-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('event', 'person')},
        ),
    ]
